site_name: LLM-Reranked Knowledge Graph Link Prediction with RL-based Prompt Policy Optimization
site_description: RL-Optimized LLM Reranking for Knowledge Graph Link Prediction

nav:
  - Home: index.md

plugins:
  - techdocs-core
